sudo: required
services:
  - docker
before_install:
  - docker build -t codemaster321/docker-react -f Dockerfile.dev .
scripts:
  - docker run -e CI=true codemaster321/docker-react npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-721270686213"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
